#!/usr/bin/env npx tsx
/**
 * run_queries.ts
 *
 * Reads modified_queries.json (written by Claude in Step 2), wraps each SQL
 * in query_template.sql, executes against Snowflake, and writes one
 * result_{alert}_{timeframe}.json per entry.
 *
 * Usage:
 *   npx tsx scripts/run_queries.ts [modified_queries.json] [output_dir]
 *
 * modified_queries.json format:
 *   [{ "alert_name": "...", "timeframe": "last_2w"|"mature_90_30", "modified_sql": "..." }]
 *
 * Required env vars:
 *   SNOWFLAKE_ACCOUNT   — e.g. "melio"
 *   SNOWFLAKE_USER      — your Melio email
 *
 * Optional env vars:
 *   SNOWFLAKE_AUTHENTICATOR  — default: EXTERNALBROWSER
 *   SNOWFLAKE_WAREHOUSE      — e.g. "RISK_WH"
 *   SNOWFLAKE_ROLE           — e.g. "RISK_ANALYST"
 */

import snowflake from 'snowflake-sdk';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const modifiedQueriesPath = process.argv[2] ?? '/tmp/risk_intel/modified_queries.json';
const outputDir = process.argv[3] ?? '/tmp/risk_intel';
const templatePath = path.resolve(__dirname, '../references/query_template.sql');

type QueryEntry = { alert_name: string; timeframe: string; modified_sql?: string; full_sql?: string };
type ResultRow = {
  MANUAL_REVIEW_LOAD: number;
  FRAUD_COUNT: number;
  BAD_RATE_PCT: number;
  FRAUD_TPV: number;
};

for (const v of ['SNOWFLAKE_ACCOUNT', 'SNOWFLAKE_USER']) {
  if (!process.env[v]) { console.error(`Missing env var: ${v}`); process.exit(1); }
}

const entries: QueryEntry[] = JSON.parse(fs.readFileSync(modifiedQueriesPath, 'utf8'));
const template = fs.readFileSync(templatePath, 'utf8');

console.log(`${entries.length} queries to run`);

async function connect(): Promise<snowflake.Connection> {
  const conn = snowflake.createConnection({
    account: process.env.SNOWFLAKE_ACCOUNT!,
    username: process.env.SNOWFLAKE_USER!,
    authenticator: (process.env.SNOWFLAKE_AUTHENTICATOR ?? 'EXTERNALBROWSER') as any,
    warehouse: process.env.SNOWFLAKE_WAREHOUSE ?? 'COMPUTE_WH',
    role: process.env.SNOWFLAKE_ROLE ?? 'ENGINEER',
  });
  await conn.connectAsync((err, c) => { if (err) throw err; });
  return conn;
}

function runQuery<T>(conn: snowflake.Connection, sql: string): Promise<T[]> {
  return new Promise((resolve, reject) => {
    conn.execute({
      sqlText: sql,
      complete: (err, _stmt, rows) => (err ? reject(err) : resolve((rows ?? []) as T[])),
    });
  });
}

// Remove trailing ORDER BY — it's invalid inside a CTE
function stripTrailingOrderBy(sql: string): string {
  return sql.replace(/\s+ORDER\s+BY\s+[\s\S]*?(?:;?\s*$)/i, '').trim();
}

function safeName(alertName: string): string {
  return alertName.replace(/[^a-z0-9]/gi, '_').toLowerCase();
}

async function main() {
  const conn = await connect();
  let passed = 0;
  let failed = 0;

  for (const entry of entries) {
    const outPath = path.join(outputDir, `result_${safeName(entry.alert_name)}_${entry.timeframe}.json`);

    try {
      // Prefer pre-built full_sql (generated by gen_modified_queries.py);
      // fall back to modified_sql + template for legacy entries.
      let fullSql: string;
      if (entry.full_sql) {
        fullSql = entry.full_sql;
      } else {
        const alertSql = stripTrailingOrderBy(entry.modified_sql ?? '');
        fullSql = template
          .replace('{MODIFIED_ALERT_SQL}', alertSql)
          .replace('{RUN_DATE}', 'CURRENT_TIMESTAMP()');
      }

      const rows = await runQuery<ResultRow>(conn, fullSql);
      const r = rows[0] ?? { MANUAL_REVIEW_LOAD: 0, FRAUD_COUNT: 0, BAD_RATE_PCT: 0, FRAUD_TPV: 0 };

      fs.writeFileSync(outPath, JSON.stringify({
        alert_name: entry.alert_name,
        timeframe: entry.timeframe,
        manual_review_load: r.MANUAL_REVIEW_LOAD ?? 0,
        fraud_count: r.FRAUD_COUNT ?? 0,
        bad_rate_pct: r.BAD_RATE_PCT ?? 0,
        fraud_tpv: r.FRAUD_TPV ?? 0,
      }, null, 2));

      console.log(`✓ ${entry.alert_name} / ${entry.timeframe}`);
      passed++;
    } catch (err: any) {
      console.error(`✗ ${entry.alert_name} / ${entry.timeframe}: ${err.message}`);
      fs.writeFileSync(outPath, JSON.stringify({
        alert_name: entry.alert_name,
        timeframe: entry.timeframe,
        manual_review_load: 0,
        fraud_count: 0,
        bad_rate_pct: 0,
        fraud_tpv: 0,
        error: err.message,
      }, null, 2));
      failed++;
    }
  }

  console.log(`\nDone: ${passed} succeeded, ${failed} failed`);
  conn.destroy(err => { if (err) console.error(err); });
}

main().catch(err => { console.error(err.message); process.exit(1); });
